services:
  web:
    build: .
    container_name: leftovers-web
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: leftovers-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: leftovers_db
      POSTGRES_USER: leftovers_user
      POSTGRES_PASSWORD: leftovers_password
    ports:
      - "5432:5432"

  static:
    image: nginx:alpine
    container_name: leftovers-static
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
